### PR TITLE
[Forge 1.7.10] Don't ignore achievements that don't have a parent achievement

### PR DESCRIPTION
**Pull request by unilock**
This includes a workaround specifically for the "Taking Inventory" achievement (`achievement.openInventory`).  
Without it, you'd see `Press '%1$s' to open your inventory.`; the workaround just replaces `%1$s` with `E`.

This is, of course, not by any means ideal, but it's late and I can't think of a better way to approach it off the top of my head. One possibility is to allow specifying arguments for translatable keys that use them via a config file or something - but I'm pretty sure this is the only achievement that needs this!?

***

I also made a branch that adds support for [ChromatiCraft's](https://reikakalseki.github.io/minecraft/mods/chromaticraft.html) "progression" notifications that are sent to chat on multiplayer servers. I don't have a screenshot, but the formatting is as such:
```
[CHAT] <gold>PlayerName</gold> has learned something new: <underlined>Progression Title</underlined>
```

Given this would also require explicit support on the Velocity side, I have no idea how to approach merging this with Yep officially. Too tired. Need sleep.

The branch: https://github.com/unilock/yep/tree/forge/1.7.10-cc

### CODE REVIEW

**Review by fooooooooooooooo — APPROVED** [review]

**Comment by fooooooooooooooo** [comment]
could add a "custom" message type to yep/velocitydiscord to support arbitrary messages

**Comment by unilock** [comment]
I was thinking about that. Maybe ChromatiCraft support should be put in a separate yep-like mod, since it's simple enough to just listen to an event and send a plugin message over a channel.  
On the Velocity side, one could configure custom message types (in the form of strings) to listen for via a config file, then specify how to format an appropriate message given an arbitrary amount of arguments.

For example:
```toml
[velocity-plugin]

[discord]
"advancement" = "> <player> has made the advancement [<title>] - <description>"
"death" = "> <player> <message>"

[discord.custom]
"chromaticraft" = "> **<player>** has learned something new: __<arg1>__"
"othermod" = "> **<player>** obtained knowledge of **<arg1>** by finding **<arg2>** in *<arg3>*"

[minecraft]
"advancement" = "<player> has made the advancement <green><hover:show_text:'<title><newline><description>'>[<title>]</hover></green>"
"death" = "<player> <message>"

[minecraft.custom]
"chromaticraft" = "<gold><player></gold> has learned something new: <underlined><arg1></underlined>"
"othermod" = "<player> obtained knowledge of <bold><arg1></bold> by finding <bold><arg2></bold> in <italic><arg3></italic>"
```

yep would then send a message like "playername:chromaticraft:progression" for ChromatiCraft, or "playername:othermod:worms:apples:forests" for the hypothetical other mod.

***

On that note: what do you think about making yep into a library? On the Velocity side, I mean - I'm not sure if I mentioned it, but [I made a plugin](https://github.com/unilock/GlobalYep) that utilizes yep in the same way that VelocityDiscord does to broadcast advancement / death messages to other Minecraft servers on the network, by which I mean I copied [`src/main/java/ooo/fooooooooooooooo/velocitydiscord/yep`](https://github.com/fooooooooooooooo/VelocityDiscord/tree/master/src/main/java/ooo/foooooooooooo/velocitydiscord/yep) in its entirety into my own plugin.  
It would be nice if, instead of doing that, I could just import yep as a `compileOnly` dependency and `@Subscribe` to `YepAdvancementEvent`, `YepDeathEvent`, `YepCustomEvent`, or what have you.

Note that I have very little understanding of how libraries work :p

**Comment by fooooooooooooooo** [comment]
@unilock I made yep in a way that would allow others to use it like a library but just never published an api package for it due to just being lazy and hard coded the api for it in velocitydiscord, I think I can make the build output an api only jar and then put that on a maven repo

**Comment by fooooooooooooooo** [comment]
could also use that opportunity to modify the plugin message format as right now it's simple and it works but it feels a bit scuffed

**Comment by unilock** [comment]
@fooooooooooooooo

> I think I can make the build output an api only jar and then put that on a maven repo

That would be awesome :)  
I think you can use [GitHub Packages](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry) as a Maven repo, if you need one?

> could also use that opportunity to modify the plugin message format as right now it's simple and it works but it feels a bit scuffed

Right, I remember an advancement that had the `|` character in its description breaking at one point :v  
Not sure what the best way to fix that would be - maybe using an unprintable unicode character or somesuch?

**Comment by fooooooooooooooo** [comment]
> Right, I remember an advancement that had the `|` character in its description breaking at one point :v Not sure what the best way to fix that would be - maybe using an unprintable unicode character or somesuch?

https://www.compart.com/en/unicode/U+241E ␞ looks like a good choice

**Pull request merged**
